return {
    "onsails/lspkind.nvim",
    opts = {
      mode = "symbol",
      symbol_map = {
        Class       = " ",
        Color       = " ",
        Constant    = " ",
        Enum        = " ",
        EnumMember  = " ",
        Event       = " ",
        Field       = " ",
        File        = " ",
        Folder      = " ",
        Function    = " ",
        Interface   = " ",
        Keyword     = " ",
        Method      = " ",
        Module      = " ",
        Operator    = " ",
        Package     = " ",
        String      = "s]",
        Struct      = " ",
        Text        = " ",
        Value       = " ",
        Variable    = " ",
        Number = "#",
        Collapsed   = " ",
        Boolean = "⊨",
        Constructor = "",
        Null = "NULL",
        Property = "",
        Reference = "",
        Snippet = "",
        Unit = "",
      },
      menu = {},
    },
    enabled = vim.g.icons_enabled,
    config = require "plugins.configs.lspkind",
}
